- name: Get disk usage of /dev/sda1
  shell: df -h | grep '/dev/sda1'
  register: disk_sda1
  changed_when: false
  tags: check_disk

- name: Extract usage percent (without % symbol)
  set_fact:
    sda1_usage_percent: "{{ disk_sda1.stdout.split()[4].replace('%', '') | int }}"
  tags: check_disk

- name: Show disk usage info
  debug:
    msg: >
      🧾 /dev/sda1 usage on {{ inventory_hostname }}: {{ sda1_usage_percent }}%
  tags: check_disk

- name: Warn if /dev/sda1 is above 90%
  debug:
    msg: |
      🚨🚨🚨 WARNING 🚨🚨🚨
      Host: {{ inventory_hostname }}
      /dev/sda1 usage is {{ sda1_usage_percent }}% – critically high!
  when: sda1_usage_percent | int > 90
  tags: check_disk
